name: Jekyll Site CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Or your desired Ruby version
          bundler-cache: true # Improves build speed

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --future

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site
